version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GAME: "Doodler"
        - RAYLIB_VERSION=5.5
    ports:
      - "8080:80"
    restart: on-failure
